### ISSUE TITLE
allow querying multi ranges

### ISSUE THREAD

**Issue by mderazon** [urbancups/node-sheets#7]
I am hitting the api limit very fast (~400 sheets in one spreadsheet)
Looks like this is the default rate limit for logged in users:

![screen shot 2016-09-23 at 10 01 02 pm](https://cloud.githubusercontent.com/assets/717076/18798045/44fd5322-81d9-11e6-9551-4102d9d7b648.png)

I have experimented a little and noticed that it's possible to get multiple sheets at once. 
We should add support for it

cc @cguedes

**Comment by mderazon** [comment]
btw, I don't know what's changed between v3 and v4, don't remember this limit in v3

**Comment by cguedes** [comment]
@mderazon you mean using https://developers.google.com/sheets/reference/rest/v4/spreadsheets.values/batchGet to get data for multiple sheets in a single reques?

> btw, I don't know what's changed between v3 and v4, don't remember this limit in v3
Me neither :-/

**Comment by mderazon** [comment]
Yup

**Comment by cguedes** [comment]
Fixed by #8.
